// Generated by FlutterFlow. API adapter of the mock backend: translates
// endpoint inputs into mock data store operations and wraps results into
// ApiCallResponses. The data + rules live in the backend-agnostic mock core.

import 'dart:convert';
import 'dart:math';

import '/flutter_flow/flutter_flow_util.dart';
import '/backend/api_requests/api_manager.dart';

import '../mock_data_store.dart';

class MockApiAdapter {
  MockApiAdapter._();

  static const Map<String, String> _jsonHeaders = {
    'content-type': 'application/json',
  };
  static final Random _random = Random();

  static Future<ApiCallResponse> listPathwaysCall({
    int? limit,
  }) async {
    final equals = <String, dynamic>{};
    final rows = MockDataStore.instance.list(
      '''cwcr1xhq''',
      MockQuery(
        equals: equals,
        orderBy: const [
          MockOrderBy('order'),
        ],
        limit: _toInt(limit),
        offset: null,
      ),
    );
    return ApiCallResponse(
      _applyResponseTemplate(
        '''<rows>''',
        rows: rows,
      ),
      _jsonHeaders,
      200,
    );
  }

  static Future<ApiCallResponse> listDailyScriptureCall({
    int? limit,
  }) async {
    final equals = <String, dynamic>{};
    final rows = MockDataStore.instance.list(
      '''0tezerta''',
      MockQuery(
        equals: equals,
        orderBy: const [],
        limit: _toInt(limit),
        offset: null,
      ),
    );
    return ApiCallResponse(
      _applyResponseTemplate(
        '''<rows>''',
        rows: rows,
      ),
      _jsonHeaders,
      200,
    );
  }

  static Future<ApiCallResponse> listEncouragementsCall({
    int? limit,
  }) async {
    final equals = <String, dynamic>{};
    final rows = MockDataStore.instance.list(
      '''3imsgiaw''',
      MockQuery(
        equals: equals,
        orderBy: const [],
        limit: _toInt(limit),
        offset: null,
      ),
    );
    return ApiCallResponse(
      _applyResponseTemplate(
        '''<rows>''',
        rows: rows,
      ),
      _jsonHeaders,
      200,
    );
  }

  static Future<ApiCallResponse> listAnnouncementsCall({
    int? limit,
  }) async {
    final equals = <String, dynamic>{};
    final rows = MockDataStore.instance.list(
      '''req5rzo3''',
      MockQuery(
        equals: equals,
        orderBy: const [],
        limit: _toInt(limit),
        offset: null,
      ),
    );
    return ApiCallResponse(
      _applyResponseTemplate(
        '''<rows>''',
        rows: rows,
      ),
      _jsonHeaders,
      200,
    );
  }

  static Future<ApiCallResponse> getUserProfileCall({
    String? id,
  }) async {
    final row = MockDataStore.instance.getById('''gzi06lle''', id);
    if (row == null) {
      return _response('{"error": "Not found"}', 404, const {});
    }
    return ApiCallResponse(row, _jsonHeaders, 200);
  }

  static Future<ApiCallResponse> createUserProfileCall({
    String? fullName,
    String? preferredLanguage,
    String? ffApiRequestBody,
  }) async {
    final payload = _decodeJsonObject(ffApiRequestBody);

    final row = MockDataStore.instance.create('''gzi06lle''', payload);
    return ApiCallResponse(row, _jsonHeaders, 201);
  }

  static Future<void> _simulateLatency(int latencyMs, int jitterMs) async {
    final totalMs =
        latencyMs + (jitterMs > 0 ? _random.nextInt(jitterMs + 1) : 0);
    if (totalMs > 0) {
      await Future.delayed(Duration(milliseconds: totalMs));
    }
  }

  static bool _shouldSimulateError(double errorRate) =>
      errorRate > 0 && _random.nextDouble() < errorRate;

  static ApiCallResponse _response(
    String body,
    int statusCode,
    Map<String, String> headers,
  ) =>
      ApiCallResponse(
        _tryDecode(body),
        {..._jsonHeaders, ...headers},
        statusCode,
      );

  static dynamic _tryDecode(String body) {
    if (body.isEmpty) {
      return null;
    }
    try {
      return jsonDecode(body);
    } catch (_) {
      return body;
    }
  }

  static Map<String, dynamic> _decodeJsonObject(String? body) {
    if (body == null || body.isEmpty) {
      return {};
    }
    try {
      final decoded = jsonDecode(body);
      return decoded is Map ? Map<String, dynamic>.from(decoded) : {};
    } catch (_) {
      return {};
    }
  }

  /// Wraps operation results into the configured response shape. Tokens:
  /// <rows>, <row>, <totalCount>.
  static dynamic _applyResponseTemplate(
    String template, {
    dynamic rows,
    dynamic row,
    int? totalCount,
  }) {
    final encoded = template
        .replaceAll('<rows>', jsonEncode(rows ?? []))
        .replaceAll('<row>', jsonEncode(row))
        .replaceAll('<totalCount>', jsonEncode(totalCount ?? 0));
    return _tryDecode(encoded);
  }

  static int? _toInt(dynamic value) =>
      value is int ? value : int.tryParse('${value ?? ''}');

  /// Converts a 1-based page number into a row offset.
  static int? _pageOffset(int? page, int? limit) =>
      page == null ? null : (page - 1) * (limit ?? 20);
}
