// Generated by FlutterFlow. Runtime toggle between the live backend and the
// built-in mock backend.

import 'package:flutter/foundation.dart';

import 'mock_data_store.dart';

enum FFDataSourceMode { live, mock }

class FFDataSource {
  FFDataSource._();

  /// Startup override, e.g. `flutter run --dart-define=FF_DATA_SOURCE=mock`.
  static const String _dartDefineOverride =
      String.fromEnvironment('FF_DATA_SOURCE');

  /// The current data source mode. Listen to react to runtime switches.
  static final ValueNotifier<FFDataSourceMode> modeNotifier =
      ValueNotifier(_initialMode);

  static FFDataSourceMode get _initialMode {
    switch (_dartDefineOverride) {
      case 'mock':
        return FFDataSourceMode.mock;
      case 'live':
        return FFDataSourceMode.live;
      default:
        return FFDataSourceMode.live;
    }
  }

  static FFDataSourceMode get mode => modeNotifier.value;

  static bool get isMock => mode == FFDataSourceMode.mock;

  /// Switches the data source at runtime. Widgets holding responses from the
  /// previous source keep them until rebuilt.
  static void setMode(FFDataSourceMode newMode) => modeNotifier.value = newMode;

  /// Discards all runtime changes to mock data and re-seeds the store.
  static void resetMockData() => MockDataStore.instance.reset();
}
