// Generated by FlutterFlow. Seed data and per-dataset configuration for the
// mock data store.

import 'mock_data_store.dart';

abstract class MockSeedData {
  /// Dataset configurations keyed by dataset key.
  static const Map<String, MockDatasetConfig> datasets = {
    'cwcr1xhq': MockDatasetConfig(
      idFieldName: 'id',
      idStrategy: MockIdStrategy.autoIncrementInt,
      seedRowsJson:
          '''[{"id":"pathway-come-and-see","title":{"en":"Come & See","es":"Ven y Ve","ur":"آؤ اور دیکھو"},"description":{"en":"A 14-day introduction to following Jesus.","es":"Una introducción de 14 días para seguir a Jesús.","ur":""},"durationDays":14,"status":"published","stableId":"come-and-see","order":1},{"id":"pathway-growing-in-faith","title":{"en":"Growing in Faith","es":"Creciendo en la Fe","ur":""},"description":{"en":"A second sample pathway proving no app-code change is needed to add content.","es":"","ur":""},"durationDays":21,"status":"draft","stableId":"growing-in-faith","order":2}]''',
    ),
    '0tezerta': MockDatasetConfig(
      idFieldName: 'id',
      idStrategy: MockIdStrategy.autoIncrementInt,
      seedRowsJson:
          '''[{"id":"scripture-01-01","date":"01-01","verseRef":"John 3:16","text":{"en":"For God so loved the world...","es":"Porque de tal manera amó Dios al mundo...","ur":""},"status":"published"},{"id":"scripture-01-02","date":"01-02","verseRef":"Psalm 23:1","text":{"en":"The Lord is my shepherd; I shall not want.","es":"El Señor es mi pastor; nada me faltará.","ur":""},"status":"published"}]''',
    ),
    '3imsgiaw': MockDatasetConfig(
      idFieldName: 'id',
      idStrategy: MockIdStrategy.autoIncrementInt,
      seedRowsJson:
          '''[{"id":"encouragement-01-01","date":"01-01","quote":{"en":"Be strong and courageous.","es":"Sé fuerte y valiente.","ur":""},"attribution":"Joshua 1:9","status":"published"},{"id":"encouragement-01-02","date":"01-02","quote":{"en":"This is the day the Lord has made.","es":"Este es el día que hizo el Señor.","ur":""},"attribution":"Psalm 118:24","status":"published"}]''',
    ),
    'req5rzo3': MockDatasetConfig(
      idFieldName: 'id',
      idStrategy: MockIdStrategy.autoIncrementInt,
      seedRowsJson:
          '''[{"id":"announcement-welcome","title":{"en":"Welcome to Kingdom Heirs","es":"","ur":""},"body":{"en":"We are so glad you are here. Start your Come & See journey today.","es":"","ur":""},"audience":"all"}]''',
    ),
    'gzi06lle': MockDatasetConfig(
      idFieldName: 'id',
      idStrategy: MockIdStrategy.autoIncrementInt,
      seedRowsJson:
          '''[{"id":"demo-user","fullName":"Demo Member","role":"admin","preferredLanguage":"en","surveyResponses":{}}]''',
    ),
  };
}
