/// Book names (Genesis..Revelation, canonical order) as published in each
/// language's approved API.Bible translation. English uses the names in
/// bible_page_widget.dart. Generated from the API.Bible /books endpoint.
const kBibleBookNames = <String, List<String>>{
  'es': [
    "Génesis",
    "Éxodo",
    "Levítico",
    "Números",
    "Deuteronomio",
    "Josué",
    "Jueces",
    "Rut",
    "1 Samuel",
    "2 Samuel",
    "1 Reyes",
    "2 Reyes",
    "1 Crónicas",
    "2 Crónicas",
    "Esdras",
    "Nehemías",
    "Ester",
    "Job",
    "Salmos",
    "Proverbios",
    "Eclesiastés",
    "Cantares",
    "Isaías",
    "Jeremías",
    "Lamentaciones",
    "Ezequiel",
    "Daniel",
    "Oseas",
    "Joel",
    "Amós",
    "Abdías",
    "Jonás",
    "Miqueas",
    "Nahúm",
    "Habacuc",
    "Sofonías",
    "Hageo",
    "Zacarías",
    "Malaquías",
    "San Mateo",
    "San Marcos",
    "San Lucas",
    "San Juan",
    "Hechos",
    "Romanos",
    "1 Corintios",
    "2 Corintios",
    "Gálatas",
    "Efesios",
    "Filipenses",
    "Colosenses",
    "1 Tesalonicenses",
    "2 Tesalonicenses",
    "1 Timoteo",
    "2 Timoteo",
    "Tito",
    "Filemón",
    "Hebreos",
    "Santiago",
    "1 Pedro",
    "2 Pedro",
    "1 Juan",
    "2 Juan",
    "3 Juan",
    "Judas",
    "Apocalipsis",
  ],
  'ur': [
    "پیدائش",
    "خُروج",
    "اَحبار",
    "گِنتی",
    "اِستِثنا",
    "یہوشُعؔ",
    "قُضاۃ",
    "رُوتؔ",
    "1 شموایلؔ",
    "2 شموایلؔ",
    "1 سلاطین",
    "2 سلاطین",
    "1 تواریخ",
    "2 تواریخ",
    "عزرا",
    "نحمیاہ",
    "ایسترؔ",
    "ایُّوب",
    "زبُور",
    "امثال",
    "واعظ",
    "غزل الغزلات",
    "یَشعیاہ",
    "یرمیاہؔ",
    "نوحہ",
    "حزقی ایل",
    "دانی ایل",
    "ہوشِیعؔ",
    "یُوایلؔ",
    "عامُوسؔ",
    "عبدیاہؔ",
    "یُوناہؔ",
    "میکاہؔ",
    "ناحُومؔ",
    "حبقُّوقؔ",
    "صفنیاہؔ",
    "حگّیؔ",
    "زکریاؔہ",
    "ملاکیؔ",
    "متّی",
    "مرقُس",
    "لُوقا",
    "یُوحنّا",
    "اعمال",
    "رُومیوں",
    "1 کُرِنتھِیوں",
    "2 کُرِنتھِیوں",
    "گلتیوں",
    "اِفِسیوں",
    "فِلپّیوں",
    "کلُسّیِوں",
    "1 تھِسّلُنیِکیوں",
    "2 تھِسّلُنیِکیوں",
    "1 تِیمُتھِیُس",
    "2 تِیمُتھِیُس",
    "طِطُس",
    "فِلیمون",
    "عِبرانیوں",
    "یعقوب",
    "1 پطرس",
    "2 پطرس",
    "1 یُوحنّا",
    "2 یُوحنّا",
    "3 یُوحنّا",
    "یہُوداہؔ",
    "مُکاشفہ",
  ],
  'lg': [
    "Olubereberye",
    "Okuva",
    "Ebyabaleevi",
    "Okubala",
    "Ekyamateeka Olwokubiri",
    "Yoswa",
    "Balam",
    "Luusi",
    "1 Samwiri",
    "2 Samwiri",
    "1 Bassekabaka",
    "2 Bassekabaka",
    "1 Ebyomumirembe",
    "2 Ebyomumirembe",
    "Ezera",
    "Nekkemiya",
    "Eseza",
    "Yobu",
    "Zabbuli",
    "Engero",
    "Omubuulizi",
    "Oluyimba",
    "Isaaya",
    "Yeremiya",
    "Okukungubaga",
    "Ezeekyeri",
    "Danyeri",
    "Koseya",
    "Yoweeri",
    "Amosi",
    "Obadiya",
    "Yona",
    "Mikka",
    "Nakkumu",
    "Kaabakuuku",
    "Zeffaniya",
    "Kaggayi",
    "Zekkaliya",
    "Malaki",
    "Matayo",
    "Makko",
    "Lukka",
    "Yokaana",
    "Ebikolwa byʼAbatume",
    "Abaruumi",
    "1 Abakkolinso",
    "2 Abakkolinso",
    "Abaggalatiya",
    "Abaefeso",
    "Abafiripi",
    "Abakkolosaayi",
    "1 Basessaloniika",
    "2 Basessaloniika",
    "1 Timoseewo",
    "2 Timoseewo",
    "Tito",
    "Firemooni",
    "Abaebbulaniya",
    "Yakobo",
    "1 Peetero",
    "2 Peetero",
    "1 Yokaana",
    "2 Yokaana",
    "3 Yokaana",
    "Yuda",
    "Okubikkulirwa",
  ],
};
